name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run: |
          flake8 .
          echo "Linted all the Python files successfully"
      - name: Fail job if linting errors
        if: ${{ failure() }}
        run: exit 1

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          jshint ./server/database --strict
          echo "Linted all the JS files successfully"
      - name: Fail job if linting errors
        if: ${{ failure() }}
        run: exit 1
