name: 'Lint Code'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8 black

      - name: Run Python Linter and Formatter
        run: |
          black . --check
          find . -name "*.py" -exec flake8 --max-line-length=100 {} +
          echo "Linted and formatted Python files successfully"
      - name: Fail job if linting errors
        if: ${{ failure() }}
        run: exit 1

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JavaScript Linter
        run: |
          find . -name "*.js" -exec jshint --strict {} +
          echo "Linted all the JavaScript files successfully"
      - name: Fail job if linting errors
        if: ${{ failure() }}
        run: exit 1
