name: 'Lint Code'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Python Linter
        run: |
          find . -name "*.py" -exec flake8 --max-line-length=120 {} +
          echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JavaScript Linter
        run: |
          find . -name "*.js" -exec jshint {} +
          echo "Linted all the JavaScript files successfully"
